spring.datasource.url=${ENERGY_DB_URL:jdbc:postgresql://energy-ops-db:5432/energyops}
spring.datasource.username=${ENERGY_DB_USERNAME:energyops}
spring.datasource.password=${ENERGY_DB_PASSWORD:energyops}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.h2.console.enabled=false
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

energy.ml.enabled=true
energy.ml.base-url=${ENERGY_ML_BASE_URL:http://energy-ops-ml:8001}
