spring.application.name=energy-ops-platform
spring.profiles.default=demo
spring.jpa.open-in-view=false
spring.jackson.time-zone=America/Edmonton
spring.jackson.serialization.write-dates-as-timestamps=false
spring.web.resources.cache.period=0
spring.web.resources.cache.cachecontrol.no-store=true
spring.web.resources.cache.cachecontrol.must-revalidate=true

server.port=8080

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=never
management.metrics.tags.application=${spring.application.name}
management.prometheus.metrics.export.enabled=true
management.info.env.enabled=true

info.app.name=Energy Ops Canada
info.app.region=Canada
info.app.profile=${spring.profiles.active:${spring.profiles.default}}

logging.level.root=INFO
logging.level.ca.yisong.energyops=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF

energy.security.jwt.secret=change-this-demo-secret-to-a-longer-string-for-production
energy.security.jwt.expiration-hours=10
energy.demo.data.file=energy_ops_sensor_readings_500.csv
energy.ml.enabled=false
energy.ml.base-url=http://localhost:8001
energy.alert.cooldown-hours=6
